version: "3"
services:
    mysql-server:
        image: mysql:5.6
        container_name: mysql-server
        environment:
            MYSQL_DATABASE: zabbix
            MYSQL_USER: zabbix
            MYSQL_PASSWORD: zabbix
            MYSQL_ROOT_PASSWORD: 1234qwer
        restart: always
    zabbix-server-mysql :
        image: zabbix/zabbix-server-mysql
        container_name: zabbix-server-mysql
        links:
            - "mysql-server"
        environment:
            MYSQL_DATABASE: zabbix
            MYSQL_USER: zabbix
            MYSQL_PASSWORD: zabbix
            MYSQL_ROOT_PASSWORD: 1234qwer
        ports:
            - "10051:10051"
        restart: always
    zabbix-web-nginx-mysql:
        image: zabbix/zabbix-web-nginx-mysql
        container_name: zabbix-web-nginx-mysql
        links:
            - "mysql-server"
            - "zabbix-server-mysql"
        ports:
            - "80:80"
        environment:
            MYSQL_DATABASE: zabbix
            MYSQL_USER: zabbix
            MYSQL_PASSWORD: zabbix
            MYSQL_ROOT_PASSWORD: 1234qwer
        restart: always
